version: 2

project_name: zap

before:
  hooks:
    - go mod tidy

builds:
  - id: zap
    main: ./cmd/zap
    binary: zap
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: blackcoderx
    name: zap
  draft: false
  prerelease: auto
  name_template: "ZAP v{{.Version}}"
  header: |
    ## ZAP v{{.Version}}

    AI-powered API debugging that understands your codebase.
  footer: |
    ---

    **Full Changelog**: https://github.com/blackcoderx/zap/compare/{{ .PreviousTag }}...{{ .Tag }}


