version: 2

project_name: zap

before:
  hooks:
    - go mod tidy

builds:
  - id: zap
    main: ./cmd/zap
    binary: zap
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: blackcoderx
    name: zap
  draft: false
  prerelease: auto
  name_template: "ZAP v{{.Version}}"
  header: |
    ## ZAP v{{.Version}}

    AI-powered API debugging that understands your codebase.
  footer: |
    ---

    **Full Changelog**: https://github.com/blackcoderx/zap/compare/{{ .PreviousTag }}...{{ .Tag }}

# Homebrew tap configuration
brews:
  - name: zap
    repository:
      owner: blackcoderx
      name: homebrew-zap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/blackcoderx/zap"
    description: "AI-powered API debugging that understands your codebase"
    license: "MIT"
    install: |
      bin.install "zap"
    test: |
      system "#{bin}/zap", "version"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    skip_upload: auto

# Scoop bucket configuration
scoops:
  - name: zap
    repository:
      owner: blackcoderx
      name: scoop-bucket
      branch: main
      token: "{{ .Env.SCOOP_BUCKET_TOKEN }}"
    homepage: "https://github.com/blackcoderx/zap"
    description: "AI-powered API debugging that understands your codebase"
    license: "MIT"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    commit_msg_template: "Scoop manifest update for {{ .ProjectName }} version {{ .Tag }}"
    skip_upload: auto
